version: "3.9"
services:
    django:
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile
        image: defilepsie
        container_name: defilepsie_container
        depends_on:
            - postgres
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        command: /app/compose/django/start


    postgres:
        container_name: defilepsie
        image: postgres:latest
        working_dir: /app
        restart: always
        env_file:
            - ./.env
        ports:
            - "29907:5432"
        volumes:
            - "defilepsie:/var/lib/postgresql/data"

volumes:
    defilepsie: